name: C++ CI

on:
  pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Install dependencies
      run: sudo apt update && sudo apt install binutils nasm python3 dos2unix

    - name: Check line spaces
      run: |
        pushd $GITHUB_WORKSPACE
        ci-extra/check-lines.sh
        popd

    - name: Check formatting
      run: |
        ci-extra/check-asm-formatting.py

    - name: Build
      run: nasm -felf64 wordcount.asm && ld wordcount.o -o wordcount

    - name: Test
      run: ./test.py
